[package]
name = "triangle_stripper"
version = "0.1.0"
edition = "2024"
description = "Utility program to brute-force search a triangle strip order of triangle list vertex indices"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
